-- ==================================================================
-- EDA (Exploratry Data Analytics)
-- ==================================================================

-- Find the date of first and last order
-- How many years of sales are available

SELECT
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	YEAR(MAX(order_date)) - YEAR(MIN(order_date)) AS order_range_years 
FROM
	dwh_gold.fact_sales
	

-- Find youngest and oldest customer
	
SELECT
	MIN(birthdate) AS oldest_birthdate,
	TIMESTAMPDIFF(YEAR, MIN(birthdate), CURRENT_DATE()) AS oldest_age,
	MAX(birthdate) AS youngest_birthdate,
	TIMESTAMPDIFF(YEAR, MAX(birthdate), CURRENT_DATE()) AS youngest_age
FROM
	dwh_gold.dim_customers
	

-- Find the total sales

SELECT SUM(sales_amount) AS total_sales
FROM dwh_gold.fact_sales

-- Find how many items are sold

SELECT SUM(quantity) AS total_qunatity
FROM dwh_gold.fact_sales

-- Find average selling price

SELECT ROUND(AVG(price), 2) AS avg_selling_price
FROM dwh_gold.fact_sales

-- Find the total number of orders

SELECT COUNT(order_number) AS total_orders
FROM dwh_gold.fact_sales

SELECT COUNT(DISTINCT order_number) AS total_orders -- gives more accurate number
FROM dwh_gold.fact_sales

-- Find total number of products

SELECT COUNT(product_key) AS total_products 
FROM dwh_gold.dim_products
	
SELECT COUNT(DISTINCT product_key) AS total_products 
FROM dwh_gold.dim_products

-- Find total number of customers

SELECT COUNT(customer_key) AS total_customers
FROM dwh_gold.dim_customers

-- Find total number of customers that has placed an order

SELECT COUNT(DISTINCT customer_key) AS customers_placed_orders
FROM dwh_gold.dim_customers



-- Generate a Report that shows all key metrics of the business

SELECT 'total_sales' AS measure_name, SUM(sales_amount) AS measure_value FROM dwh_gold.fact_sales
UNION ALL
SELECT 'total_qunatity', SUM(quantity) FROM dwh_gold.fact_sales
UNION ALL
SELECT 'avg_selling_price', ROUND(AVG(price), 2) FROM dwh_gold.fact_sales
UNION ALL
SELECT 'total_products', COUNT(DISTINCT product_key) FROM dwh_gold.dim_products
UNION ALL
SELECT 'total_customers', COUNT(customer_key) FROM dwh_gold.dim_customers
UNION ALL
SELECT 'customers_placed_orders', COUNT(DISTINCT customer_key) FROM dwh_gold.dim_customers



-- Magnitude Analysis
-- -------------------------------------------

-- Find total customers by country

SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM
	dwh_gold.dim_customers
GROUP BY
	country
ORDER BY
	total_customers DESC

-- Find total customers by gender

SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM
	dwh_gold.dim_customers
GROUP BY
	gender
ORDER BY
	total_customers DESC

-- Find total products by category

SELECT
	category,
	COUNT(product_key) AS total_products
FROM
	dwh_gold.dim_products
GROUP BY
	category
ORDER BY total_products DESC

-- What is the average cost in each category?

SELECT
	category,
	ROUND(AVG(product_cost), 2) AS avg_prd_cost
FROM
	dwh_gold.dim_products
GROUP BY
	category
ORDER BY
	avg_prd_cost DESC

-- What is total revenue generated for each catergory?

SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM
	dwh_gold.fact_sales f LEFT JOIN dwh_gold.dim_products p
	ON p.product_key = f.product_key
GROUP BY
	category
ORDER BY
	total_revenue DESC


-- Find total revenue is generated by each customer

SELECT
	c.customer_key,	
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM
	dwh_gold.fact_sales f LEFT JOIN dwh_gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY
	total_revenue DESC

-- What is the distribtion of sold items across countries?

SELECT
	c.country,
	SUM(f.quantity) AS sold_qunatity
FROM
	dwh_gold.fact_sales f JOIN dwh_gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY
	c.country
ORDER BY
	sold_qunatity DESC



-- Ranking Analysis
-- ----------------------------------


-- Which 5 products generate the highest revenue

SELECT
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM
	dwh_gold.dim_products p JOIN dwh_gold.fact_sales f
	ON p.product_key = f.product_key
GROUP BY
	p.product_name 
ORDER BY total_revenue DESC
LIMIT 5

-- same using WINDOW FUNCTION

SELECT
	*
FROM (
	SELECT
		p.product_name,
		SUM(f.sales_amount) AS total_revenue,
		DENSE_RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS revenue_rnk
	FROM
		dwh_gold.dim_products p JOIN dwh_gold.fact_sales f
		ON p.product_key = f.product_key
	GROUP BY
		p.product_name)t
WHERE revenue_rnk <= 5;

-- What are 5 wrost performing products in terms of sales

SELECT
	p.product_name,
	SUM(f.sales_amount) total_revenue
FROM
	dwh_gold.dim_products p JOIN dwh_gold.fact_sales f
	ON p.product_key = f.product_key
GROUP BY
	p.product_name 
ORDER BY total_revenue ASC
LIMIT 5

-- same using WINDOW FUNCTION

SELECT
	*
FROM (
	SELECT
		p.product_name,
		SUM(f.sales_amount) AS total_revenue,
		DENSE_RANK() OVER (ORDER BY SUM(f.sales_amount) ASC) AS revenue_rnk
	FROM
		dwh_gold.dim_products p JOIN dwh_gold.fact_sales f
		ON p.product_key = f.product_key
	GROUP BY
		p.product_name)t
WHERE revenue_rnk <= 5;


-- 3 customers with fewest order placed (this will take too long due to LEFT JOIN and then DISTINCT)

SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT f.order_number) AS order_count
FROM
	dwh_gold.dim_customers c LEFT JOIN dwh_gold.fact_sales f
	ON c.customer_key = f.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY
	order_count ASC
LIMIT 3


-- Optimizing above query to get result much faster
-- Our approach is to use 2 CTE's

WITH order_count AS -- This CTE calculates the total_orders per customer_key and then ORDER BY them and select 3 as per order
(
    SELECT
        customer_key,
        COUNT(DISTINCT order_number) AS total_orders
    FROM dwh_gold.fact_sales
    GROUP BY customer_key
    ORDER BY total_orders ASC, customer_key ASC
    LIMIT 3
),

customer AS -- This CTE will just find the customer first and last name along with all the details of 1st CTE as....
(			-- we used INNER JOIN to find names as per customes_key as LEFT JOIN will show the result for those customers
    SELECT	-- along with these who never made any order and have NULL in their total_orders
        o.*,
        c.first_name,
        c.last_name
    FROM dwh_gold.dim_customers c
    JOIN order_count o
        ON c.customer_key = o.customer_key
)

SELECT *
FROM customer;











